CREATE TABLE [dbo].[Articles]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(200) NOT NULL,
	[EAN13] VARCHAR(13) NOT NULL, 
	[Price] FLOAT NOT NULL, 
	[Actif] Bit NOT NULL DEFAULT 1
)
